### ISSUE TITLE
Does the library support KSP?

### ISSUE THREAD

**Issue by mochadwi** [mars885/hilt-binder#4]

**Comment by mars885** [comment]
The lib does not support KSP at the moment.

I definitely have in mind to add KSP support in the future. Just not at the moment, since KSP is still in very early development. I think when KSP beta/rc release comes out, I'll release a KSP artifact.

**Comment by mars885** [comment]
The KSP support has been added. See #24 for PR and [README's section](https://github.com/mars885/hilt-binder#ksp) for more info.
