### ISSUE TITLE
This annotation is not applicable to target 'top level property with delegate'

### ISSUE THREAD

**Issue by DHosseiny** [mars885/hilt-binder#43]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/9461116/163668307-4cf0bef0-02ae-408b-8d25-225525bc7f72.png">
I think it is useful for top-level properties with delegates. As you see this is useful for DataStore preferences.

**Comment by mars885** [comment]
'@BindType` is not applicable to Kotlin top-level properties.
