### ISSUE TITLE
Migration away from JCenter

### ISSUE THREAD

**Issue by jakoss** [mars885/hilt-binder#5]
Since Bintray is going away, are you planning to migrate to library to Maven Central or JitPack?

Great job btw, it is baffling to me why the Hilt does not have to built in

**Comment by mars885** [comment]
Yes, I'm aware of that JCenter is shutting down.

I'm planning to migrate to Maven Central in the next week or two. Stay tuned for more info.

**Comment by mars885** [comment]
See #8.
