### ISSUE TITLE
InstallIn custom component

### ISSUE THREAD

**Issue by jakoss** [mars885/hilt-binder#6]
For now, installIn requires usage of `Component` enum. I have to install my class in custom component. Can i do that right now? If not - i think it's crucial to have this. In my case - i'm trying to get rid of boilerplate when using Maverics with Hilt. I have such component:
```kotlin
@MavericksViewModelScoped
@DefineComponent(parent = SingletonComponent::class)
interface MavericksViewModelComponent
```

**Comment by mars885** [comment]
First of all, thanks for the feedback.

You are right in that custom components are not supported by the library at this moment. However, I'm definitely planning to add support for them in the upcoming release.

**Comment by mars885** [comment]
Custom components are now supported in the `1.0.0-alpha02` version. See [changelog](https://github.com/mars885/hilt-binder/blob/master/CHANGELOG.md#version-100-alpha02-2021-04-25) for more info.

**Comment by jakoss** [comment]
Works perfectly, thank you!
